### ISSUE TITLE
using docforia for philology

### ISSUE THREAD

**Issue by eroux** [marcusklang/docforia#4]
Hi, Docforia looks very good and I'd like to consider using it, I just have a question on the conceptual model:

Let's say I have two witnesses of a text:

W1:  `docforia is good`
W2:  `docforia are good`

and I have some recorded emendations:

W2-fixed:  `are`  -->  `is`

and I would like to express that in one text with multiple layer:

layer 0: `docforia is good`
layer 1: W2 says  `is` --> `are`
layer 2, on top of layer 1: I say it should be `are` --> `is`

and then on top of layer 0 and 2, I would have all sorts of NLP annotations.

Is that something docforia can model?

**Comment by marcusklang** [comment]
If I understand what you want to accomplish, then yes this is possible with Docforia. However, please compare it with the Docria alternative (I think it is a better alterantive).

Just to verify that I understand the problem correctly because I am not entirely sure:
You have a single reference text, two persons witness this text and makes emendations to this text. In the end, the final goal is to merge these changes from 1 to N witnesses into a final version. In between, and after there might be many NLP layers referencing the original and final version of text.

If above is correct I would model it like this with Docforia:
- Node Layer 0 is a context reference (where in the original text)
- Node Layer 1 contains emendations by witnesses, (one field for which witness, what change, and possibly exactly where), Witness 2 would change `is` --> `are`, context
- Edge Layer 0 binds Layer 0 and Layer 1
- Node Layer 2 contains the joined/merged version.
- Edge layer 1 binds Layer 1 and Layer 2

**Docria alternative**
I would however recommend you take a look at Docria (https://github.com/marcusklang/docria) it is the successor of Docforia and is the project I actively develop and use, it is in my mind the better option here. It is faster, safer and simpler to use in my mind.

With Docria it would be very similar but it is more direct (edges are optional):

- Text 1: Original text
- Layer 0: Frame of context (span to Text1), all witness changes in Layer 1 (node reference list)
- Layer 1: Witness (int), exact location of change (span to Text1), the change (string)
- Layer 2: Frame of context (node reference to layer 0), selected changes (node reference list to layer 1 - if there are multiple changes), merged text (string).

Then you can add NLP layers on top of these layers.

Docria also adds the possibility to add a second text representing the merged version for Layer 2. This might simplify code when adding NLP layers, as their references would be context consistent, easy to debug the resulting sentence and compare original and merged version.

Docforia's edges introduces some complexity something Docria can avoid because it is a Hypergraph (nodes and edges are the same, allowing a single node to reference many nodes).

**Comment by eroux** [comment]
ok excellent thanks! I got the name confused, sorry, I was indeed asking about doctria... that looks very excellent, thanks a lot! Another question I have is how is docforia funded? are you working on it on your free time or as part of a project you're paid for?

**Comment by marcusklang** [comment]
Docria/Docforia is funded indirectly by research I am doing as a Ph.D student. I use it as tooling in my research.
